### ISSUE TITLE
making constant height constraint not working

### ISSUE THREAD

**Issue by benjiwheeler** [SnapKit/SnapKit#116]
I'm getting different behavior in my app if I do:
(within a UITableViewHeaderFooterView subclass, fyi)

self.contentView.snp_makeConstraints { (make) -> Void in
    make.height.equalTo(125.0) // doesn't work -- resulting height in the app is about 50
}

vs. if I do:

self.contentView.addConstraint(NSLayoutConstraint(item: self.contentView, attribute: NSLayoutAttribute.Height, relatedBy: NSLayoutRelation.Equal, toItem: nil, attribute: NSLayoutAttribute.NotAnAttribute, multiplier: 1.0, constant: 125.0))
// DOES work -- resulting height in app is 125.0

These should work exactly the same, right? All of my other SnapKit constraints seem to work fine!

**Comment by robertjpayne** [comment]
@benjiwheeler hmm I'll look into this – typically the constraint is added to it's parent view but in the case of pure attributes it should replicate the functionality you're expecting.

**Comment by benjiwheeler** [comment]
Thanks! I guess I'm not sure which superview SnapKit would be adding this constraint to.

Could it be that the resulting SnapKit constraint is the equivalent of my verbose version's constraint if it were added to self instead of self.contentView?

**Comment by robertjpayne** [comment]
@benjiwheeler you're starting off the constraint with `self.contentView` so it should add width and height attributes directly to `self.contentView` since they are set to constant values and not another view.

Sorry I don't have immediate time to dig in on this, I had a quick look at the code though and didn't see anything weird. Do you by chance have any time to setup a small sample project? I know it's minimal but would make it quicker to dive into.

**Comment by robertjpayne** [comment]
@benjiwheeler so `SnapKit` always installs constraints on at least the view's superview rather than itself hence this is failing. I'm going to see if there is a graceful way to fix this…

**Comment by robertjpayne** [comment]
@benjiwheeler ok this is in develop now -- if you are solely pinning to width or height or both to a numerical constant it will install the constraints directly on the view rather than it's superview.
