### ISSUE TITLE
It might be good to add support for label to constraints

### ISSUE THREAD

**Issue by manesvenom** [SnapKit/SnapKit#132]
Hi,

It might be good to add support for label to constraints that it can be used for reference and delete those constraints with the label specified.

e.g. in Eric Sadun book Auto Layout Demystified
for (NSLayoutConstraint *constraint in [view constraintsNamed:LINE_BUILDING_NAME matchingView:view])
            [constraint remove];

**Comment by robertjpayne** [comment]
@manesvenom you can use the `snp_prepareConstraints` method and store them however you like for future removal.

You can also set `snp_label` on them, though it's mostly for debugging purposes you could query it too.

We're refraining from trying to build any sort of auto removal system based on a tag, or label because they all have caveats.

**Comment by manesvenom** [comment]
Thank you, It is better to make use snp_prepareConstraints instead.
