### ISSUE TITLE
error build with Xcode 7

### ISSUE THREAD

**Issue by Henry4Zhang** [SnapKit/SnapKit#146]
cannot build with Xcode 7 with Cocoapods installed

**Comment by Taarna** [comment]
You should probably share more details. How does your podfile look like? What's the error you're getting?

**Comment by iPermanent** [comment]
# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'
platform :ios, '8.0'
use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

target 'HRSwiftTest' do

pod 'SnapKit', '~> 0.12.0'
pod 'Alamofire', '~> 1.2.3'
pod 'AFNetworking', '~> 2.5.4'
pod 'Masonry', '~> 0.6.2'
pod 'FMDB', '~> 2.5'
pod 'SVProgressHUD', '~> 1.1.3'
pod 'SDWebImage', '~> 3.7.2'

end
I think that's the problem caused by swift new change,as you know swift is still change every small new version, the error shows seemed some wrong in build. Like & and | symbols. As this framework not updated for about 2 months, I used the latest Xcode 7.0 from app store.Thanks

**Comment by robertjpayne** [comment]
@iPermanent can you try setting snapkit to `0.14.0` which is the latest release with Swift 2.0 support?

**Comment by iPermanent** [comment]
@robertjpayne  But where I use pod search the latest version is 0.12.0,maybe this pod not update on pod source? thanks

**Comment by iPermanent** [comment]
@robertjpayne Thanks, maybe it's the problem of my pod repo version, I will update it to the latest and try  again, thanks very much for your patience and effort.

**Comment by robertjpayne** [comment]
@iPermanent from terminal:

```
Roberts-MacBook-Pro:contactapp-rn robertjpayne$ pod search SnapKit


-> SnapKit (0.14.0)
   Harness the power of auto layout with a simplified, chainable, and compile time safe syntax.
   pod 'SnapKit', '~> 0.14.0'
   - Homepage: https://github.com/SnapKit/SnapKit
   - Source:   https://github.com/SnapKit/SnapKit.git
   - Versions: 0.14.0, 0.13.0, 0.12.0, 0.11.0, 0.10.0 [master repo]
Roberts-MacBook-Pro:contactapp-rn robertjpayne$
```

**Comment by robertjpayne** [comment]
Feel free to re-open if this does not resolve the issue.
