### ISSUE TITLE
right as if don't work

### ISSUE THREAD

**Issue by glorybird** [SnapKit/SnapKit#188]
leftVC.view.snp_makeConstraints { (make) -> Void in
            make.left.equalTo(containVC.view.frame.origin.x)
            make.right.equalTo(containVC.view.frame.origin.x + 20)
            make.top.equalTo(containVC.view.frame.origin.y + 20)
            make.bottom.equalTo(containVC.view.frame.origin.y + containVC.view.frame.height)
        }

the width is not 20

so I can only use the following method

leftVC.view.snp_makeConstraints { (make) -> Void in
            make.left.equalTo(containVC.view.frame.origin.x)
            make.width.equalTo(20)
            make.top.equalTo(containVC.view.frame.origin.y + 20)
            make.bottom.equalTo(containVC.view.frame.origin.y + containVC.view.frame.height)
        }

**Comment by robertjpayne** [comment]
@glorybird you want to make constraints to SnapKit attributes rather than constant values. When you do something like:

`make.left.equalTo(otherView.frame.origin.x + 20)` it's setting the constraint to a constant value of the otherview's current x position + 20.

Instead you want to do:

`make.left.equalTo(otherView.snp_left).offset(20)` which will constrain it to the left side + a constant 20pt.

**Comment by glorybird** [comment]
thank you very much ！
