### ISSUE TITLE
NSException problem with swift

### ISSUE THREAD

**Issue by RMPtc** [SnapKit/SnapKit#196]
Hi, by using the NSException instead of ErrorType in swift it does not allow the use of the native do-catch mechanism and only use the try-catch from Objective-C like [SwiftTryCatch](https://github.com/ravero/SwiftTryCatch). I think this is helpful for developers.

Keep the good work.

**Comment by robertjpayne** [comment]
@RMPtc this is actually 100% intentional. These exceptions are programmer errors that should be dealt with before deploying.

While we could allow them to be caught it doesn't really make sense as it will mean you've not setup your Auto Layout properly and will get inconsistent/weird results.

In my eyes its far better to get these as crash reports and fix them.
