### ISSUE TITLE
UICollectionViewCell with SnapKit not working in iOS 10

### ISSUE THREAD

**Issue by yonasstephen** [SnapKit/SnapKit#261]
### New Issue Checklist

* [v ] I have looked at the [Documentation](http://snapkit.io/docs)
* [v ] I have read the [F.A.Q.](http://snapkit.io/faq)

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | ios
 Platform Version        | 10.0
 SnapKit Version         | should be latest in cocoapods? 0.19.0
 Integration Method      | cocoapods
 

### Issue Description

Hi guys,

I tried to use SnapKit to AutoLayout my UICollectionView so that each cell will auto-resize according to its content. But I couldn't make it work. I posted similar question in StackOverflow here: [http://stackoverflow.com/questions/38595602/uicollectionviewcell-with-autolayout-not-working-in-ios-10](http://stackoverflow.com/questions/38595602/uicollectionviewcell-with-autolayout-not-working-in-ios-10). Please refer to my SO post for the details.

If you want to rewrite the issues posted in SO here, let me know. Need your SnapKit expert advice! Much thanks!

**Comment by robertjpayne** [comment]
@yonasstephen have you tried using a regular `UILabel` rather than `TTTAttributedLabel`? My guess is something is bad with `TTTAttributedLabel` intrinsic content sizing.

You may also need to play with the compression/hugging priorities on the label/content view as it looks like it's compressing them.

My general guess is you have set a flexible width on the contentView and then just ask the label to fit left and right to the contentView.

You may try to be more explicit on the contentView.

**Comment by yonasstephen** [comment]
@robertjpayne Hi Robert, sadly it is yeah the TTTAttributedLabel, it does some black magic inside :( Oh well at least the Auto Layout works now. Thanks!

**Comment by robertjpayne** [comment]
@yonasstephen well at least you know!
