### ISSUE TITLE
Swift 3.0 Support

### ISSUE THREAD

**Issue by simonnarang** [SnapKit/SnapKit#267]
When will swift 3 be supported

**Comment by robertjpayne** [comment]
To everyone that reaches this issue. Swift 3.0 support is tracking in the `feature/0.40.0` branch. It's part of a bigger migration but also includes Swift 3.0. 

It's easiest to target the head of that branch with Cocoapods/Carthage rather than try to pin to a beta release as it's moving fast with every Xcode release.

At this point it's beta quality, and may have unknown issues etc…

**Comment by simonnarang** [comment]
Okay thanks

**Comment by simplealina** [comment]
Hi. Just wanted to point out that Xcode 8 beta 6 got released yesterday. It is causing several issues with the feature/0.40.0 branch. Thanks in advance
