### ISSUE TITLE
Constraint conflict when calling updateOffset()

### ISSUE THREAD

**Issue by murphm8** [SnapKit/SnapKit#280]
### New Issue Checklist

* [X] I have looked at the [Documentation](http://snapkit.io/docs)
* [X] I have read the [F.A.Q.](http://snapkit.io/faq)

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | iOS
 Platform Version        | 9.3.4
 SnapKit Version         | 0.22.0
 Integration Method      | manually
 

### Issue Description

I am setting a constraint in my view as follows:

        dialogView.snp_makeConstraints {
            make in
            make.leading.trailing.equalTo(self).inset(26.0)
            make.height.lessThanOrEqualTo(maxHeight)
            centerConstraint = make.center.equalTo(self).constraint
        }

In an animation controller I call:

        view.centerConstraint.updateOffset(100)

At this call I get a debug message about conflicting constraints. Is that normal? Should I be doing something like uninstall() or deactivate() first?

**Comment by igorefremov** [comment]
@murphm8 

No, this is expected behavior.  Your leading/trailing constraints are conflicting with the center constraint AFTER you apply an offset to the center.

Think of make.center as make.centerX.centerY, which means that when you apply an offset to the centerX, .leading and .trailing will conflict because they imply an offset of 0 for .centerX

**Comment by murphm8** [comment]
That makes sense. Thanks for clarifying. I changed it to use centerY and the errors went away.
