### ISSUE TITLE
update unexisting constraint in feature/0.40.0

### ISSUE THREAD

**Issue by NSLogMeng** [SnapKit/SnapKit#284]
### New Issue Checklist

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | ios/osx/tvos
 Platform Version        | *
 SnapKit Version         | feature/0.40.0
 Integration Method      | cocoapods
 

### Issue Description
Hi, I'm using Snakit on Xcode8 beta 6 with feature/0.40.0, when i write 

```
someView.snp.updateConstraints({ (make) in
     make.someNotExistingContraint.equalTo(someOtherView)
 })
```

it will go there `fatalError("Updated constraint could not find existing matching constraint to update: \(layoutConstraint)")`

In the last release version, this would add the unexisting constraint to view. 
But now, I think it's mean `updateConstaints` only allow update existing constraint? or there is a new way to do this?

thanks for your work!

**Comment by igorefremov** [comment]
@NSLogMeng 

This is expected behavior (https://twitter.com/robertjpayne/status/761445181228933120). 

Use snp_makeConstraints if you are adding new constraints, and want to keep the existing constraints.  However, if you want to remove the old constraints first, and then add new constraints, use snp_remakeConstraints. 

The docs state that "...if you are only **updating the constant value** of the constraint you can use the method snp_updateConstraints instead of snp_makeConstraints."

**Comment by robertjpayne** [comment]
@NSLogMeng as @igorefremov has pointed out this is now intentional behaviour. My reasoning for this is as follows

* `makeConstraints` - should be used to create new constraints and append them to the existing ones
* `remakeConstraints` should be used to reset and then `makeConstraints`. And it should really be used in place of `updateConstraints` in nearly all circumstances.

I'm even half tempted to deprecate `updateConstraints` and make users either use `remakeConstraints` or hold onto a reference for the constraint. `updateConstraints` has resulted in ridiculous amounts of questions and most of the time it can't be used anyways. If you're after high performance (e.g. touch event) based constraint updating it's very likely you want to store a copy of the constraint and update it directly.

**Comment by NSLogMeng** [comment]
@igorefremov @robertjpayne 
oh, I understand. thank you :)   ╰(￣▽￣)╮

**Comment by robertjpayne** [comment]
@NSLogMeng hope it doesn't cause you too much trouble! In the long run I think it'll prevent more errors.

**Comment by NSLogMeng** [comment]
yeah, I will change my habit.╮(╯▽╰)╭
but your words seems reasonable. 👍
