### ISSUE TITLE
How do we make constraints equal?

### ISSUE THREAD

**Issue by mozeryansky** [SnapKit/SnapKit#480]
### New Issue Checklist

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)
* [x] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | ios
 Platform Version        | 11.0
 SnapKit Version         | 4.0.0
 Integration Method      | cocoapod
 

### Issue Description

How do we make constraints equal to another constraint?

I tried `make.height.equalTo(make.width)`, but that had a compiler error. Right now I am using `make.height.equalTo(view.snp.width)`. But I rather reference self or something similar. I noticed that snp has a private reference to the view, can that be made public?

**Comment by robertjpayne** [comment]
@mozeryansky you're correct you need to use the `snp` DSL you cannot use `self`.

The reason it has a private reference to the view is because it needs to know what the constraints are to be attached to. It's private because it's an implementation detail and not something that should be relied upon (some constraints have no views but are layout guides etc…)
