### ISSUE TITLE
multipliedBy not working as expected

### ISSUE THREAD

**Issue by alouanemed** [SnapKit/SnapKit#564]
* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)
* [x] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                |  ios
 Platform Version        | 12
 SnapKit Version       | 4.2.
 Integration Method      | pod
 

### Issue Descriptions

I am trying to use multipliedBy constraint in one of my views and it is not working as expected, 

This seem to work perfectly fine : 
`make.width.equalTo(view.width/ 2) `
Instead of this :      
`make.width.equalTo(view.width).multipliedBy(0.5)`
I wonder why is that?

**Comment by OlafAndreas** [comment]
I've been digging, and the usage of `width.equalTo(_:)` is a bit unclear.
I will attempt to give an understanding of what's happening under the hood.

By writing `make.width.equalTo(view.width)`, a constant is made that holds the value of `view.width` and the multiplier provided by `.multipliedBy(0.5)` gets ignored.

An excerpt from `ConstraintMakerRelatable.swift` show us what happens if the constraint target is a constant:
```
} else if let other = other as? ConstraintConstantTarget {
    related = ConstraintItem(target: nil, attributes: ConstraintAttributes.none)
    constant = other
}
```
Notice the target is set to `nil` and the constant is set to `other`(which will be whatever the value of view.width is). Now when the target is nil, any provided multiplier have no target to multiply, which brings us to how a constraint is made.

Let's say we have a parentView with the width of 500, but based on the previous info the parentView in this case would be `nil` and the formula would look like this:
```
// item1.attribute = multiplier * item2.attribute + constant
childView.width = 0.5 * parentView.width + 500.0
```

This would result in `childView.width = 500.0`.

#### Correct Usage ?

The correct usage seems to be either:
`make.width.equalTo(parentView).multipliedBy(0.5)`
or
`make.width.equalToSuperview().multipliedBy(0.5)`

These two solutions will make the `parentView` be used as a `ConstraintView` and passed along to the constraint formula. The constant will also be set to `0.0`.

An excerpt of `ConstraintMakerRelatable.swift`:
```
} else if let other = other as? ConstraintView {
    related = ConstraintItem(target: other, attributes: ConstraintAttributes.none)
    constant = 0.0
}
```

Hope this helps! :)
