### ISSUE TITLE
How to make three equal labels in superView in a row

### ISSUE THREAD

**Issue by magic3584** [SnapKit/SnapKit#641]
### New Issue Checklist

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)
* [x] I have filled out this issue template.

### Issue Description

I wanna make three equal labels in superView in a row.

I tried this but it crashed `*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'NSLayoutConstraint for <UILabel: 0x153d34a90; frame = (0 0; 0 0); text = '0'; userInteractionEnabled = NO; layer = <_UILabelLayer: 0x28248c8c0>>: A multiplier of 0 or a nil second item together with a location for the first attribute creates an illegal constraint of a location equal to a constant. Location attributes must be specified in pairs.'`
```` swift
labelView.addSubview(topLabel)
topLabel.snp.makeConstraints { (make) in
     
     //crashed first row           
     make.left.equalTo(labelView.snp_width).multipliedBy(1/3*index)
     make.top.equalTo(0)
     make.width.equalToSuperview().dividedBy(3)
     make.height.equalTo(37)
}
````

**Comment by mmdock** [comment]
Why not just add three labels to a horizontal UIStackView that fills proportionally?
```
        let stackView = UIStackView(arrangedSubviews: labels)
        stackView.axis = .horizontal
        stackView.distribution = .fillProportionally
        stackView.alignment = .center
        stackView.spacing = spacing

        for label in labels{
            label.snp.makeConstraints({make in
                make.height.equalToSuperview()
            })
        }

        stackView.snp.makeConstraints({ make in
           // stackView constraints.
        })

```

**Comment by magic3584** [comment]
@mmdock Excellent solutions! But I'm still wondering that it is possible to set left constraint using percentage.

**Comment by mmdock** [comment]
> @mmdock Excellent solutions! But I'm still wondering that it is possible to set left constraint using percentage. Like I wanna add two separate line between three labels

So, i am taking your comment of "I wanna add two separate lines between three labels" to mean you want spacing between the labels.  

This is what the `stackView.spacing = spacing`.  Your `spacing` value you set will be the spacing between the labels.  I do not think this affects the spacing on the left and right labels to the left/right edges of the stackview.

**Comment by mmdock** [comment]
taking a second look at your original code attempt:

`make.left.equalTo(labelView.snp_width).multipliedBy(1/3*index)` 

So assuming you are doing this in a loop, wouldn't your first index be a 0 value and hence be the cause of your crash?  Assuming you fixed that by offsetting it 1, then I believe the width of the `labelView ` is currently 0, hence why this is occurring.  You will probably have to set the `labelView ` width before doing this.

**Comment by magic3584** [comment]
@mmdock Hi, I wanna do to achieve like this
![WX20191109-135158@2x.png](https://i.loli.net/2019/11/09/RIptlVJFAw1usSq.png)

three labels are equal width in **labelView**, and two line in **lineView** above **labelView**.

At the very beginning , I do `make.left.equalTo(labelView.snp_width).multipliedBy(1/3*index)` in a loop because I wanna label's left is 0、1/3、2/3 of **labelView's** width.

Now I arrange three labels in a stackView, but I still have no way to place the two lines. Neither `make.left.equalTo(lineView.snp_width).multipliedBy(0.3)` nor `make.centerX.equalTo(lineView.centerX).multipliedBy(0.3)` worked.

**Comment by mmdock** [comment]
@magic3584  Are you trying to not have any space between the labels, or is are these lines views?  

If they are views, then simply create those views and add the into the horizontal stack view between your labels and give them height and appropriate width.

However, since they will have a different width from your labels, you cannot use `.fillProportionally` for the distribution (if i recall correctly).  

If you are wanting 0 spacing, between the labels and just want to add a border to the sides of each label, you can make a custom subclass and draw border lines on the sides of each label, something similar to the following in the `draw()` function:

    let cgContext = UIGraphicsGetCurrentContext()
    cgContext?.move(to: CGPoint(x: rect.minX, y: rect.minY))
    cgContext?.addLine(to: CGPoint(x: rect.minX, y: rect.maxY))
    cgContext?.setStrokeColor(UIColor.black.cgColor)
    cgContext?.setLineWidth(1.0)
    cgContext?.strokePath()

This will add a line on the left side of the UIView.  You can duplicate for the right and change the thickness.

Or you can see a rather interesting extension here: https://stackoverflow.com/questions/17355280/how-to-add-a-border-just-on-the-top-side-of-a-uiview

Haven't checked it out myself, but looks like it would be pretty useful.

additionally, if NOT using the stackview approach, it would be easier (probably, in your case) to have temporary pointers to the previously set label.


```
var previousLabel: UILabel?
for label in labels{
            labelView.addSubview(label)
            label.snp.makeConstraints { make in
                _ = previousLabel == nil ? make.left.equalTo(0) : make.left.equalTo(previousLabel!.snp.right).offset(/*Spacing between the labels desired*/)
                make.width.equalToSuperview().dividedBy(3)
                make.top.bottom.equalTo(0)
            }
            previousLabel = label
}//end if
previousLabel?.snp.makeConstraints{ make in 
    make.right.equalToSuperview()
}
```

**Comment by magic3584** [comment]
@mmdock Thanks for your generous help, you're a nice man!
