### ISSUE TITLE
Terser syntax

### ISSUE THREAD

**Issue by cannyboy** [SnapKit/SnapKit#93]
I was looking at https://github.com/Draveness/DKChainableAnimationKit and it has a nice syntax:

    view.animation.makeScale(2.0).spring.animate(1.0)

Would it possible to have a similar syntax for SnapKit, so that `make` is not passed into a closure. So instead of:

    view.snp_makeConstraints { (make) -> Void in
          make.width.height.equalTo(50)
          make.center.equalTo(self.view)
    }

.. you have ...:

    view.constrain.width.height.equalTo(50)
    view.constrain.center.equalTo(view)

Perhaps even with an animation if the view has an existing constraint:

    view.constrain.width.height.equalTo(75).animate(1.2)

**Comment by jhurray** [comment]
@cannyboy  the whole reason they have you make constraints in closures/blocks is because apple's  API has a very specific protocol for dealing with constraint changes. I havent read SnapKit too closely, but I am guessing that they capture that block and execute it in the **updateConstraints** function. See [this](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIView_Class/index.html#//apple_ref/doc/uid/TP40006816-CH3-SW170) for details. This is why it has been hard to add constraint animations to JHChainableAnimations (and therefore DKChainableAnimationKit). You shouldn't just update constraints wherever you feel like it in your code. Thats how shit gets broken

**Comment by robertjpayne** [comment]
@cannyboy @jhurray:

* Closure blocks allow easier scoping/encapsulation of constraints for each view. Rather than having 50 lines of code bunched up that are making constraints for 10 different views we can produce more readable code by ensuring each view's constraints are scoped and easily viewed.
* Closure blocks are necessary for `remakeConstraints` and `updateConstraints` as both perform some operations before and after the closure completes.
*  I'd argue that your proposed syntax is actually less terse as you must lead every constraint with the 
`viewNameWhichMayBeReallyLong.constrain.` rather than just `make.`
* The animation chaining syntax you've provided is not flexible and would require magic under the hood. What if that constraint doesn't currently exist? What if needs to update an existing constraint or remove one? What if you have a few different animation blocks to run and want to set the easing equations etc?

In general Auto Layout doesn't play extremely nice with animations. Luckily with iOS 8.0+ the `view.layer.tranform` property places quite nice with Auto Layout. I recommend using SnapKit to setup your base layout constraints and then using `view.layer.transform` for any animations.

**Comment by jhurray** [comment]
@cannyboy See the autoLayout section of my repo and lead the caveats if you are interested.




Robert is right, auto layout and animations don't really play nicely. Transforms are a great way to animate layout constraints. If you are looking to do more complicated stuff with anchor points that is frame based use my repo or other animation kits. 




9 times out of ten when making an app I'll use the constraints / transform approach. 



—
